package com.hisaberp.sales.internal;

public enum DocumentType {
    QUOTE, ORDER, INVOICE, CREDIT_NOTE, DELIVERY_NOTE, RETURN_DELIVERY,
    PAYMENT_RECEIPT, PURCHASE_ORDER, PURCHASE_INVOICE, GOODS_RECEIPT, PURCHASE_CREDIT_NOTE
}
