package com.minierp.purchase.internal;

/**
 * INBOUND = goods coming in from the supplier (normal reception, stock-in).
 * RETURN  = goods going back to the supplier (auto-generated by a purchase
 * credit note / avoir, stock-out). Mirror of the sales DeliveryType.
 */
public enum GoodsReceiptType { INBOUND, RETURN }
