package com.hisaberp.purchase.internal;

import com.hisaberp.shared.persistence.TenantAwareEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Bon de Réception (BRC). Mirror of the sales {@code Delivery} (BL), anchored to
 * a purchase invoice. INBOUND receipts post a PURCHASE_RECEIPT stock-in (and lots
 * for tracked products); RETURN receipts — auto-generated by a purchase credit
 * note — post a PURCHASE_RETURN stock-out.
 */
@Entity
@Table(name = "goods_receipts",
        uniqueConstraints = @UniqueConstraint(name = "uk_goods_receipts_tenant_number", columnNames = {"tenant_id", "number"}),
        indexes = {
                @Index(name = "idx_goods_receipts_party", columnList = "party_id"),
                @Index(name = "idx_goods_receipts_invoice", columnList = "purchase_invoice_id"),
                @Index(name = "idx_goods_receipts_status", columnList = "status")
        })
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
class GoodsReceipt extends TenantAwareEntity {

    @Id @GeneratedValue @Column(columnDefinition = "uuid")
    private UUID id;

    @Column(nullable = false, length = 30)
    private String number;

    @Column(name = "party_id", nullable = false, columnDefinition = "uuid")
    private UUID partyId;

    @Column(name = "purchase_invoice_id", nullable = false, columnDefinition = "uuid")
    private UUID purchaseInvoiceId;

    @Column(name = "warehouse_id", columnDefinition = "uuid")
    private UUID warehouseId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private GoodsReceiptStatus status = GoodsReceiptStatus.PENDING;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private GoodsReceiptType type = GoodsReceiptType.INBOUND;

    @Column(name = "scheduled_date")
    private LocalDate scheduledDate;

    @Column(name = "received_at")
    private Instant receivedAt;

    @Column(name = "received_by", columnDefinition = "uuid")
    private UUID receivedBy;

    @Column(length = 1000)
    private String notes;
}
